COMMENT = An Extremely fast, In-Memory JSON and Interface Library for Modern C++
VERSION = 7.0.2
REVISION = 0
CATEGORIES = libs
PKGNAME = glaze
HOMEPAGE = https://github.com/stephenberry/glaze
ARCHIVE = glaze-7.0.2.tar.gz
LINK = https://github.com/stephenberry/glaze/archive/v7.0.2/glaze-7.0.2.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = glaze-7.0.2
BUILD_OPTION = -Dglaze_ENABLE_FUZZING=OFF \
	-Dglaze_DEVELOPER_MODE=OFF \
	-Dglaze_INSTALL_CMAKEDIR=/usr/lib/cmake/glaze \
	-DCMAKE_BUILD_TYPE=None

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
