COMMENT = Wayland event viewer
VERSION = 1.1.0
REVISION = 0
CATEGORIES = wayland
PKGNAME = wev
HOMEPAGE = https://git.sr.ht/~sircmpwn/wev
ARCHIVE = 1.1.0.tar.gz
LINK = https://git.sr.ht/~sircmpwn/wev/archive/1.1.0.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = wev-1.1.0
MAKEOPT = MANDIR=/usr/share/man

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
