COMMENT = The hyprland cursor format, library and utilities.
VERSION = 0.1.13
REVISION = 0
CATEGORIES = libs
PKGNAME = hyprcursor
HOMEPAGE = https://github.com/hyprwm/Hyprcursor
ARCHIVE = Hyprcursor-v0.1.13.tar.gz
LINK = https://github.com/hyprwm/Hyprcursor/archive/v0.1.13/Hyprcursor-v0.1.13.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = hyprcursor-0.1.13
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
