COMMENT = a freedesktop.org compliant menu implementation based on GLib and GIO
VERSION = 4.21.0
REVISION = 0
CATEGORIES = misc
PKGNAME = garcon
HOMEPAGE = https://xfce.org/
ARCHIVE = garcon-4.21.0.tar.xz
LINK = https://archive.xfce.org/src/xfce/garcon/4.21/garcon-4.21.0.tar.xz 
SRCCD = archive
BUILD = meson
BUILDDIR = garcon-4.21.0
BUILD_OPTION = -Dgtk-doc=false \
	-Dintrospection=true \
	-Dtests=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
