COMMENT = A C header file only implementation of a typed linked list
VERSION = 1.1.0
REVISION = 0
CATEGORIES = libs
PKGNAME = tllist
HOMEPAGE = https://codeberg.org/dnkl/tllist
ARCHIVE = 1.1.0.tar.gz
LINK = https://codeberg.org/dnkl/tllist/archive/1.1.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = tllist
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
