COMMENT = Library with common API for various Cinnamon modules
VERSION = 6.6.2
REVISION = 0
CATEGORIES = misc
PKGNAME = cinnamon_desktop
HOMEPAGE = https://github.com/linuxmint/cinnamon-desktop
ARCHIVE = cinnamon-desktop-6.6.2.tar.gz
LINK = https://github.com/linuxmint/cinnamon-desktop/archive/6.6.2/cinnamon-desktop-6.6.2.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = cinnamon-desktop-6.6.2
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
