COMMENT = X11 Testing -- Resource extension library
VERSION = 1.2.5
REVISION = 0
CATEGORIES = libs
PKGNAME = libXtst
HOMEPAGE = https://wiki.freedesktop.org/xorg/
ARCHIVE = libXtst-1.2.5.tar.xz
LINK = https://www.x.org/releases/individual/lib/libXtst-1.2.5.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = libXtst-1.2.5
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
