COMMENT = JSON library implemented using Glib.
VERSION = 1.10.8
REVISION = 0
CATEGORIES = libs
PKGNAME = json_glib
HOMEPAGE = https://wiki.gnome.org/Projects/JsonGlib
ARCHIVE = json-glib-1.10.8.tar.xz
LINK = https://download.gnome.org/sources/json-glib/1.10/json-glib-1.10.8.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = json-glib-1.10.8
BUILD_OPTION = --buildtype=release \
	-Dman=false -Dtests=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
