COMMENT = X11 Xinerama extension library
VERSION = 1.1.5
REVISION = 0
CATEGORIES = libs
PKGNAME = libXinerama
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXinerama-1.1.5.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXinerama-1.1.5
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
