COMMENT = Modular Wayland compositor library
VERSION = 0.20.c6d9aa175
_WLR = 6d9aa17572c12cc22d2c9f7f0afc3e942a699d2a
REVISION = 0
CATEGORIES = libs
PKGNAME = wlroots_git
HOMEPAGE = https://gitlab.freedesktop.org/wlroots/wlroots
ARCHIVE = wlroots-${_WLR}.tar.gz
LINK = https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/${_WLR}/wlroots-${_WLR}.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = wlroots-${_WLR}
BUILD_OPTION = -Dexamples=false -Dxwayland=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
