COMMENT = Modular Wayland compositor library
VERSION = 0.20.c3336d288
_WLR = 3336d28813698eb6fba908a4dbcf38b79ed2e3db
REVISION = 0
CATEGORIES = libs
PKGNAME = wlroots_git
HOMEPAGE = https://gitlab.freedesktop.org/wlroots/wlroots
ARCHIVE = wlroots-${_WLR}.tar.gz
LINK = https://gitlab.freedesktop.org/wlroots/wlroots/-/archive/${_WLR}/wlroots-${_WLR}.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = wlroots-${_WLR}
BUILD_OPTION = -Dexamples=false -Dxwayland=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
