COMMENT = Simple terminal emulator based on linux kernel mode setting
VERSION = 9.3.3
REVISION = 0
CATEGORIES = sys
PKGNAME = kmscon
HOMEPAGE = https://github.com/kmscon/kmscon
ARCHIVE = v9.3.3.tar.gz
LINK = https://github.com/kmscon/kmscon/archive/refs/tags/v9.3.3.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = kmscon-9.3.3
BUILD_OPTION = -Delogind=enabled -Dtests=false -Dmulti_seat=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
