COMMENT = Simple terminal emulator based on linux kernel mode setting
VERSION = 9.3.1
REVISION = 0
CATEGORIES = sys
PKGNAME = kmscon
HOMEPAGE = https://github.com/kmscon/kmscon
ARCHIVE = v9.3.1.tar.gz
LINK = https://github.com/kmscon/kmscon/archive/refs/tags/v9.3.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = kmscon-9.3.1
BUILD_OPTION = -Delogind=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
