COMMENT = Improved dynamic tiling window manager
VERSION = 4.24
REVISION = 0
CATEGORIES = x11
PKGNAME = i3wm
HOMEPAGE = https://i3wm.org
ARCHIVE = i3-4.24.tar.xz
LINK = https://i3wm.org/downloads/i3-4.24.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = i3-4.24
BUILD_OPTION = -Ddocs=true -Dmans=true

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
