COMMENT = Codec designed for interactive speech and audio transmission over the Internet
VERSION = 1.6.1
REVISION = 0
CATEGORIES = audio
PKGNAME = opus
HOMEPAGE = https://www.opus-codec.org/
ARCHIVE = opus-1.6.1.tar.gz
LINK = https://downloads.xiph.org/releases/opus/opus-1.6.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = opus-1.6.1
BUILD_OPTION = -Dtests=disabled -Ddocs=disabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
