COMMENT = Hardware-accelerated video playback library
VERSION = 1.5
REVISION = 0
CATEGORIES = libs
PKGNAME = libvdpau
HOMEPAGE = https://gitlab.freedesktop.org/vdpau/libvdpau
ARCHIVE = libvdpau-1.5.tar.gz
LINK = https://gitlab.freedesktop.org/vdpau/libvdpau/-/archive/1.5/libvdpau-1.5.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = libvdpau-1.5
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
