COMMENT = X11 miscellaneous 'fixes' extension library
VERSION = 6.0.2
REVISION = 0
CATEGORIES = libs
PKGNAME = libXfixes
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXfixes-6.0.2.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXfixes-6.0.2
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

custom-build:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
