COMMENT = a minimal, lemonbar-compatible status bar for Wayland compositors.
VERSION = 0.c5e6a307e
REVISION = 0
CATEGORIES = wayland
PKGNAME = mojito
HOMEPAGE = https://git.sr.ht/~dlm/mojito 
SRCCD = git
BUILD = make
BUILDDIR = mojito
MAKEOPT = PREFIX=$(PWD)/package/usr

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
