COMMENT = modern alternative to libpng
VERSION = 0.7.4
REVISION = 0
CATEGORIES = libs
PKGNAME = libspng
HOMEPAGE = https://github.com/randy408/libspng
ARCHIVE = v0.7.4.tar.gz
LINK = https://github.com/randy408/libspng/archive/refs/tags/v0.7.4.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = libspng-0.7.4
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
