COMMENT = Introspection system for GObject-based libraries
VERSION = 1.86.0
REVISION = 1
CATEGORIES = libs
PKGNAME = gobject_introspection
HOMEPAGE = https://wiki.gnome.org/Projects/GObjectIntrospection/
ARCHIVE = gobject-introspection-1.86.0.tar.xz
LINK = https://download.gnome.org/sources/gobject-introspection/1.86/gobject-introspection-1.86.0.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = gobject-introspection-1.86.0
BUILD_OPTION = -Dtests=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
