COMMENT = nl80211 based CLI configuration utility for wireless devices
VERSION = 6.17
REVISION = 0
CATEGORIES = net
PKGNAME = iw
HOMEPAGE = https://wireless.docs.kernel.org/en/latest/en/users/documentation/iw.html
ARCHIVE = iw-6.17.tar.xz
LINK = https://www.kernel.org/pub/software/network/iw/iw-6.17.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = iw-6.17
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
