COMMENT = Hyprland implementation of wayland-scanner for C++
VERSION = 0.4.5
REVISION = 0
CATEGORIES = wayland
PKGNAME = hyprwayland_scanner
HOMEPAGE = https://github.com/hyprwm/hyprwayland-scanner
ARCHIVE = hyprwayland-scanner-v0.4.5.tar.gz
LINK = https://github.com/hyprwm/hyprwayland-scanner/archive/v0.4.5/hyprwayland-scanner-v0.4.5.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = hyprwayland-scanner-0.4.5
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
