COMMENT = X11 RandR extension library
VERSION = 1.5.4
REVISION = 0
CATEGORIES = libs
PKGNAME = libXrandr
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXrandr-1.5.4.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXrandr-1.5.4
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
