COMMENT = GNOME Unicode Charmap
VERSION = 17.0.1
REVISION = 0
CATEGORIES = font
PKGNAME = gucharmap
HOMEPAGE = https://gitlab.gnome.org/GNOME/gucharmap
ARCHIVE = gucharmap-17.0.1.tar.gz
LINK = https://gitlab.gnome.org/GNOME/gucharmap/-/archive/17.0.1/gucharmap-17.0.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = gucharmap-17.0.1
BUILD_OPTION = -Ducd_path=/usr/share/unicode -Ddocs=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
