COMMENT = Wayland compositor based on bswpm, with floating, tiling and scrolling layouts. 
VERSION = git.c02b77c64
_REV = 02b77c646f6504c388f4bee04914a1c0da8603e7
REVISION = 0
CATEGORIES = wayland
PKGNAME = bwm
HOMEPAGE = https://github.com/dy-tea/bwm
ARCHIVE = ${_REV}.tar.gz
LINK = https://github.com/dy-tea/bwm/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = bwm-${_REV}
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
