COMMENT = Wayland compositor based on bswpm, with floating, tiling and scrolling layouts. 
VERSION = git.cf7129de6
_REV = f7129de65cd3e485e49132a65cace6d37a258a36
REVISION = 0
CATEGORIES = wayland
PKGNAME = bwm
HOMEPAGE = https://github.com/dy-tea/bwm
ARCHIVE = ${_REV}.tar.gz
LINK = https://github.com/dy-tea/bwm/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = bwm-${_REV}
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
