COMMENT = Wayland compositor based on bswpm, with floating, tiling and scrolling layouts. 
VERSION = git.c214e9274
_REV = 214e9274cc2de4fd582bfea3422e92c47ff337b2
REVISION = 1
CATEGORIES = wayland
PKGNAME = bwm
HOMEPAGE = https://github.com/dy-tea/bwm
ARCHIVE = ${_REV}.tar.gz
LINK = https://github.com/dy-tea/bwm/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = bwm-${_REV}
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
