COMMENT = X11 XFree86 video mode extension library
VERSION = 1.1.6
REVISION = 0
CATEGORIES = libs
PKGNAME = libXxf86vm
HOMEPAGE = https://wiki.freedesktop.org/xorg/
ARCHIVE = libXxf86vm-1.1.6.tar.xz
LINK = https://www.x.org/releases/individual/lib/libXxf86vm-1.1.6.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = libXxf86vm-1.1.6
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
