COMMENT = The official implementation library for the hypr config language.
VERSION = 0.6.8
REVISION = 2
CATEGORIES = libs
PKGNAME = hyprlang
HOMEPAGE = https://hyprland.org/hyprlang/
ARCHIVE = v0.6.8.tar.gz
LINK = https://github.com/hyprwm/hyprlang/archive/v0.6.8.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = hyprlang-0.6.8
BUILD_OPTION = -DCMAKE_BUILD_TYPE=MinSizeRel

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
