COMMENT = Lighweight JSON parser in C
VERSION = 1.7.19
REVISION = 0
CATEGORIES = libs
PKGNAME = cjson
HOMEPAGE = https://github.com/DaveGamble/cJSON
ARCHIVE = v1.7.19.tar.gz
LINK = https://github.com/DaveGamble/cJSON/archive/v1.7.19.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = cJSON-1.7.19
BUILD_OPTION = -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	-DBUILD_SHARED_AND_STATIC_LIBS=True \
	-DCMAKE_BUILD_TYPE=MinSizeRel

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
