COMMENT = Terminal-emulator State Machine
VERSION = 4.4.2
REVISION = 0
CATEGORIES = libs
PKGNAME = libtsm
HOMEPAGE = https://github.com/kmscon/libtsm
ARCHIVE = v4.4.2.tar.gz
LINK = https://github.com/kmscon/libtsm/archive/refs/tags/v4.4.2.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = libtsm-4.4.2
BUILD_OPTION = -Dtests=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
