COMMENT = Xfce application finder
VERSION = 4.21.0
REVISION = 0
CATEGORIES = xapps
PKGNAME = xfce4_appfinder
HOMEPAGE = https://xfce.org/
ARCHIVE = xfce4-appfinder-4.21.0.tar.xz
LINK = https://archive.xfce.org/src/xfce/xfce4-appfinder/4.21/xfce4-appfinder-4.21.0.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = xfce4-appfinder-4.21.0
BUILD_OPTION = 

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
