COMMENT = HEIC/HEIF decoder for imlib2 (feh)
VERSION = 0.1.1
REVISION = 0
CATEGORIES = libs
PKGNAME = imlib2_heic
HOMEPAGE = https://github.com/vi/imlib2-heic
ARCHIVE = imlib2-heic-0.1.1.tar.gz
LINK = https://github.com/vi/imlib2-heic/archive/refs/tags/v0.1.1/imlib2-heic-0.1.1.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = imlib2-heic-0.1.1
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
