COMMENT = Oil Run-time Compiler
VERSION = 0.4.42
REVISION = 0
CATEGORIES = devel
PKGNAME = orc
HOMEPAGE = https://gstreamer.freedesktop.org/modules/orc.html
ARCHIVE = orc-0.4.42.tar.xz
LINK = https://gstreamer.freedesktop.org/src/orc/orc-0.4.42.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = orc-0.4.42
BUILD_OPTION = -Dorc-test=disabled -Dhotdoc=disabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
