COMMENT = Vulkan header files
VERSION = 1.4.313.0
REVISION = 0
CATEGORIES = libs
PKGNAME = vulkan_headers
HOMEPAGE = https://www.khronos.org/vulkan
ARCHIVE = vulkan-header-v1.4.313.0.tar.gz
LINK = https://github.com/khronosgroup/vulkan-headers/archive/refs/tags/vulkan-sdk-1.4.313.0/vulkan-header-v1.4.313.0.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = Vulkan-Headers-vulkan-sdk-1.4.313.0
BUILD_OPTION = -DVULKAN_HEADERS_ENABLE_MODULE=OFF -DCMAKE_BUILD_TYPE=None

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
