COMMENT = Documentation system for C++, C, Java, IDL and PHP
VERSION = 1.17.0
REVISION = 0
CATEGORIES = doc
PKGNAME = doxygen
HOMEPAGE = https://www.doxygen.nl/
ARCHIVE = doxygen-1.17.0.src.tar.gz
LINK = https://doxygen.nl/files/doxygen-1.17.0.src.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = doxygen-1.17.0
BUILD_OPTION = -DCMAKE_BUILD_TYPE=MinSizeRel

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
