COMMENT = A minimal status bar for Wayland compositors.
VERSION = 0.0.5.c27c50528
_REV = 27c5052832b782c5015e5b9a0dba469296e6149a
REVISION = 0
CATEGORIES = wayland
PKGNAME = ergo
HOMEPAGE = https://github.com/d4yr41n/ergo
ARCHIVE = ${_REV}.tar.gz
LINK = https://github.com/pubfnmain/ergo/archive/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = ergo-${_REV}
MAKEOPT =
override PREFIX = $(PWD)/package/usr

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
