COMMENT = X cursor management library
VERSION = 1.2.3
REVISION = 0
CATEGORIES = libs
PKGNAME = libXcursor
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXcursor-1.2.3.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXcursor-1.2.3
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
