COMMENT = X11 Video Motion Compensation extension library
VERSION = 1.0.14
REVISION = 0
CATEGORIES = libs
PKGNAME = libXvMC
HOMEPAGE = https://wiki.freedesktop.org/xorg/
ARCHIVE = libXvMC-1.0.14.tar.xz
LINK = https://www.x.org/releases/individual/lib/libXvMC-1.0.14.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = libXvMC-1.0.14
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
