COMMENT = i3-compatible window manager for Wayland 
VERSION = 0.13.c909a2ddb
_REV = 909a2ddb5fff528e735341529a028d2ef21836db
REVISION = 0
CATEGORIES = wayland
PKGNAME = sway
HOMEPAGE = https://github.com/swaywm/sway
ARCHIVE = ${_REV}.tar.gz
LINK = ${HOMEPAGE}/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = sway-${_REV}
BUILD_OPTION = -Dgdk-pixbuf=enabled -Dtray=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
