COMMENT = i3-compatible window manager for Wayland 
VERSION = 0.13.c0bf87311
_REV = 0bf8731114f8b74d97066cd1d480ed1aad735163
REVISION = 0
CATEGORIES = wayland
PKGNAME = sway
HOMEPAGE = https://github.com/swaywm/sway
ARCHIVE = ${_REV}.tar.gz
LINK = ${HOMEPAGE}/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = sway-${_REV}
BUILD_OPTION = -Dgdk-pixbuf=enabled -Dtray=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
