COMMENT = i3-compatible window manager for Wayland 
VERSION = 0.13.c97c342f9
_REV = 97c342f9e1e1f6ac640f58d53950d92bc48dd889
REVISION = 0
CATEGORIES = wayland
PKGNAME = sway
HOMEPAGE = https://github.com/swaywm/sway
ARCHIVE = ${_REV}.tar.gz
LINK = ${HOMEPAGE}/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = sway-${_REV}
BUILD_OPTION = -Dgdk-pixbuf=enabled -Dtray=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
