COMMENT = Client-side decorations library for Wayland clients
VERSION = 0.2.5
REVISION = 0
CATEGORIES = libs
PKGNAME = libdecor
HOMEPAGE = https://gitlab.freedesktop.org/libdecor/libdecor
ARCHIVE = libdecor-0.2.5.tar.gz
LINK = https://gitlab.freedesktop.org/libdecor/libdecor/-/archive/0.2.5/libdecor-0.2.5.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = libdecor-0.2.5
BUILD_OPTION = -Ddemo=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
