COMMENT = Power management for the Xfce desktop environment
VERSION = 4.21.1
REVISION = 0
CATEGORIES = xapps
PKGNAME = xfce4_power_manager
HOMEPAGE = https://goodies.xfce.org/projects/applications/xfce4-power-manager
ARCHIVE = xfce4-power-manager-4.21.1.tar.xz
LINK = https://archive.xfce.org/src/xfce/xfce4-power-manager/4.21/xfce4-power-manager-4.21.1.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = xfce4-power-manager-4.21.1
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
