COMMENT = X11 Composite extension library
VERSION = 0.4.6
REVISION = 0
CATEGORIES = libs
PKGNAME = libXcomposite
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXcomposite-0.4.6.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXcomposite-0.4.6
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

custom-build:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
