COMMENT = ID3 tag manipulation library.
VERSION = 0.16.3
REVISION = 0
CATEGORIES = libs
PKGNAME = libid3tag
HOMEPAGE = https://www.underbit.com/products/mad/
ARCHIVE = 0.16.3.tar.gz
LINK = https://codeberg.org/tenacityteam/libid3tag/archive/0.16.3.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = libid3tag
BUILD_OPTION = -DCMAKE_BUILD_TYPE=MinSizeRel \
	-DCMAKE_POLICY_VERSION_MINIMUM=3.5

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
