COMMENT = Header-only TOML config file parser and serializer for C++17.
VERSION = 3.4.0
REVISION = 0
CATEGORIES = libs
PKGNAME = tomlplusplus
HOMEPAGE = https://marzer.github.io/tomlplusplus/
ARCHIVE = tomlplusplus-v3.4.0.tar.gz
LINK = https://github.com/marzer/tomlplusplus/archive/v3.4.0/tomlplusplus-v3.4.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = tomlplusplus-3.4.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
