COMMENT = Poppler plugin adds PDF support to zathura
VERSION = 2026.02.03
REVISION = 0
CATEGORIES = libs
PKGNAME = zathura_pdf_poppler
HOMEPAGE = https://pwmt.org/projects/zathura-pdf-poppler/
ARCHIVE = zathura-pdf-poppler-2026.02.03.tar.xz
LINK = https://pwmt.org/projects/zathura-pdf-poppler/download/zathura-pdf-poppler-2026.02.03.tar.xz
SRCCD = archive
BUILD = muon
BUILDDIR = zathura-pdf-poppler-2026.02.03
BUILD_OPTION =
STRIP = no

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
