COMMENT = Library to help create and query binary XML blobs
VERSION = 0.3.25
REVISION = 0
CATEGORIES = libs
PKGNAME = libxmlb
HOMEPAGE = https://github.com/hughsie/libxmlb
ARCHIVE = ${VERSION}.tar.gz
LINK = https://github.com/hughsie/libxmlb/archive/refs/tags/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = libxmlb-${VERSION}
BUILD_OPTION = -Dgtkdoc=false -Dtests=false -Dstemmer=false -Dintrospection=true

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
