COMMENT = Wayland protocol extensions for Hyprland
VERSION = 0.7.0
REVISION = 0
CATEGORIES = libs
PKGNAME = hyprland_protocols
HOMEPAGE = https://github.com/hyprwm/hyprland-protocols
ARCHIVE = hyprland-protocols-v0.7.0.tar.gz
LINK = https://github.com/hyprwm/hyprland-protocols/archive/v0.7.0/hyprland-protocols-v0.7.0.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = hyprland-protocols-0.7.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
