COMMENT = X11 damaged region extension library
VERSION = 1.1.6
REVISION = 0
CATEGORIES = libs
PKGNAME = libXdamage
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXdamage-1.1.6.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXdamage-1.1.6
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
