COMMENT = Generates status bar for dzen2, xmobar or similar
VERSION = 2.15.cd53da19a
REVISION = 0
CATEGORIES = xapps
PKGNAME = i3status
HOMEPAGE = https://i3wm.org/i3status/
ARCHIVE = d53da19a79d68b1dc9abdb953c3d2e0497b33a7a.tar.gz
LINK = https://github.com/i3/i3status/archive/d53da19a79d68b1dc9abdb953c3d2e0497b33a7a.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = i3status-d53da19a79d68b1dc9abdb953c3d2e0497b33a7a
BUILD_OPTION = -Ddocs=true -Dmans=true -Dpulseaudio=true

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
