COMMENT = X11 Resource extension library
VERSION = 1.2.3
REVISION = 0
CATEGORIES = libs
PKGNAME = libXres
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXres-1.2.3.tar.xz
LINK = https://www.x.org/releases/individual/lib/libXres-1.2.3.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = libXres-1.2.3
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
