COMMENT = POSIX 1003.1e capabilities
VERSION = 2.78
REVISION = 0
CATEGORIES = libs
PKGNAME = libcap
HOMEPAGE = https://sites.google.com/site/fullycapable/
ARCHIVE = libcap-2.78.tar.xz
LINK = https://kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-2.78.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = libcap-2.78
MAKEOPT = BUILD_CC=gcc CC=gcc lib=lib prefix=/usr GOLANG=no

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
