COMMENT = JSON for Modern C++
VERSION = 3.12.0
REVISION = 0
CATEGORIES = libs
PKGNAME = nlohmann_json
HOMEPAGE = https://github.com/nlohmann/json
ARCHIVE = nlohmann-json-3.12.0.tar.gz
LINK = https://github.com/nlohmann/json/archive/v3.12.0/nlohmann-json-3.12.0.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = json-3.12.0
BUILD_OPTION = -DJSON_MultipleHeaders=ON

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
