COMMENT = wayland compositor base wlroots and scenefx (dwm but wayland)
VERSION = 0.12.5.c1e1d41e6
REVISION = 0
CATEGORIES = wayland
PKGNAME = mangowc
HOMEPAGE = https://github.com/DreamMaoMao/mangowc
COMMIT = 1e1d41e626aa12057c03ec79ed11bcc5619f6748
ARCHIVE = ${COMMIT}.tar.gz
LINK = https://github.com/DreamMaoMao/mangowc/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = mango-${COMMIT}

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
