COMMENT = wayland compositor base wlroots and scenefx (dwm but wayland)
VERSION = 0.12.5.c8216cacb
REVISION = 0
CATEGORIES = wayland
PKGNAME = mangowc
HOMEPAGE = https://github.com/DreamMaoMao/mangowc
COMMIT = 8216cacb3b0f7c1de7bec6abd4be8b5acfe94b8e
ARCHIVE = ${COMMIT}.tar.gz
LINK = https://github.com/DreamMaoMao/mangowc/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = mango-${COMMIT}
BUILD_OPTION = -Ddefault_library=both

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
