COMMENT = wayland compositor base wlroots and scenefx (dwm but wayland)
VERSION = 0.12.5.c0d8aedf6
REVISION = 0
CATEGORIES = wayland
PKGNAME = mangowc
HOMEPAGE = https://github.com/DreamMaoMao/mangowc
COMMIT = 0d8aedf691bb740290ad5c447d157a8d26a35ffe
ARCHIVE = ${COMMIT}.tar.gz
LINK = https://github.com/DreamMaoMao/mangowc/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = mango-${COMMIT}

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
