COMMENT = less primitive primitive drawing library for wayland
VERSION = 0.c9ed9f16c
REVISION = 0
CATEGORIES = libs
PKGNAME = neuwld
HOMEPAGE = https://git.sr.ht/~shrub900/neuwld
SRCCD = git
BUILD = make
BUILDDIR = neuwld

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
