COMMENT = X11 Input extension library
VERSION = 1.8.2
REVISION = 0
CATEGORIES = libs
PKGNAME = libXi
HOMEPAGE = https://www.x.org
ARCHIVE = libXi-1.8.2.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXi-1.8.2
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
