COMMENT = Application launcher for wlroots-based Wayland compositors
VERSION = 1.13.1
REVISION = 0
CATEGORIES = wayland
PKGNAME = fuzzel
HOMEPAGE = https://codeberg.org/dnkl/fuzzel/
ARCHIVE = ${VERSION}.tar.gz
LINK = https://codeberg.org/dnkl/fuzzel/archive/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = fuzzel

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
