COMMENT = FreeType-based font drawing library for X
VERSION = 2.3.9
REVISION = 0
CATEGORIES = libs
PKGNAME = libXft
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXft-2.3.9.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXft-2.3.9
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
