COMMENT = X11 Video extension library
VERSION = 1.0.13
REVISION = 0
CATEGORIES = libs
PKGNAME = libXv
HOMEPAGE = https://wiki.freedesktop.org/xorg/
ARCHIVE = libXv-1.0.13.tar.xz
LINK = https://www.x.org/releases/individual/lib/libXv-1.0.13.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = libXv-1.0.13
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

custom-build:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
