COMMENT = XML parsing library, version 2
VERSION = 2.15.4
REVISION = 0
CATEGORIES = libs
PKGNAME = libxml2
HOMEPAGE = https://gitlab.gnome.org/GNOME/libxml2
ARCHIVE = libxml2-${VERSION}.tar.xz
LINK = https://download.gnome.org/sources/libxml2/2.15/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = libxml2-${VERSION}
BUILD_OPTION = -Dicu=enabled -Dlegacy=enabled -Dpython=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
