COMMENT = Desktop manager for Xfce
VERSION = 4.20.1
REVISION = 0
CATEGORIES = misc
PKGNAME = xfdesktop
HOMEPAGE = https://xfce.org/
ARCHIVE = xfdesktop-4.20.1.tar.bz2
LINK = https://archive.xfce.org/src/xfce/xfdesktop/4.20/xfdesktop-4.20.1.tar.bz2 
SRCCD = archive
BUILD = meson
BUILDDIR = xfdesktop-4.20.1
BUILD_OPTION = -Dtests=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
