COMMENT = File manager for Xfce
VERSION = 4.21.4
REVISION = 3
CATEGORIES = xapps
PKGNAME = thunar
HOMEPAGE = https://docs.xfce.org/xfce/thunar/start
ARCHIVE = thunar-4.21.4.tar.xz
LINK = https://archive.xfce.org/src/xfce/thunar/4.21/thunar-4.21.4.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = thunar-4.21.4
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
