COMMENT = Windowing concept abstraction library for X11 and Wayland.
VERSION = 4.20.5
REVISION = 0
CATEGORIES = libs
PKGNAME = libxfce4windowing
HOMEPAGE = https://gitlab.xfce.org/xfce/libxfce4windowing
ARCHIVE = libxfce4windowing-4.20.5.tar.bz2
LINK = https://archive.xfce.org/src/xfce/libxfce4windowing/4.20/libxfce4windowing-4.20.5.tar.bz2
SRCCD = archive
BUILD = meson
BUILDDIR = libxfce4windowing-4.20.5
BUILD_OPTION = -Dgtk-doc=false \
	-Dwayland=enabled \
	-Dx11=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
