COMMENT = A multipurpose and versatile launcher / picker for Hyprland
VERSION = 0.1.6
REVISION = 1
CATEGORIES = wayland
PKGNAME = hyprlauncher
HOMEPAGE = https://github.com/hyprwm/hyprlauncher
ARCHIVE = hyprlauncher-0.1.6.tar.gz
LINK = https://github.com/hyprwm/hyprlauncher/archive/v0.1.6/hyprlauncher-0.1.6.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = hyprlauncher-0.1.6
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
