COMMENT = Adwaita icon theme
VERSION = 49.0
REVISION = 0
CATEGORIES = icon
PKGNAME = adwaita_icon_theme
HOMEPAGE = https://gitlab.gnome.org/GNOME/adwaita-icon-theme
ARCHIVE = adwaita-icon-theme-49.0.tar.xz
LINK = https://download.gnome.org/sources/adwaita-icon-theme/49/adwaita-icon-theme-49.0.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = adwaita-icon-theme-49.0
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
