COMMENT = Light-weight, simple and fast XML parser for C++ with XPath support
VERSION = 1.15
REVISION = 0
CATEGORIES = libs
PKGNAME = pugixml
HOMEPAGE = https://pugixml.org
ARCHIVE = pugixml-1.15.tar.gz
LINK = https://github.com/zeux/pugixml/archive/refs/tags/v1.15/pugixml-1.15.tar.gz
SRCCD = archive
BUILD = cmake
BUILDDIR = pugixml-1.15
BUILD_OPTION = -DPUGIXML_BUILD_TESTS="OFF"

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
