COMMENT = Vala rewrite of SimplePanel 
VERSION = 24.03.c82005703
_REV = 820057031abfb8cdfe8a38424c6cdeb01f023ea5
REVISION = 0
CATEGORIES = xapps
PKGNAME = vala_panel
HOMEPAGE = https://gitlab.com/vala-panel-project/vala-panel
ARCHIVE = vala-panel-${_REV}.tar.gz
LINK = ${HOMEPAGE}/-/archive/${_REV}/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = vala-panel-${_REV}
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
