COMMENT = C++ wrapper for the GLib toolkit
VERSION = 2.66.8
REVISION = 0
CATEGORIES = libs
PKGNAME = glibmm2.66
HOMEPAGE = https://www.gtkmm.org/
ARCHIVE = glibmm-2.66.8.tar.xz
LINK = https://download.gnome.org/sources/glibmm/2.66/glibmm-2.66.8.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = glibmm-2.66.8
BUILD_OPTION = -Dbuild-documentation=false -Dbuild-examples=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
