COMMENT = Settings manager for xfce
VERSION = 4.21.1
REVISION = 0
CATEGORIES = xapps
PKGNAME = xfce4_settings
HOMEPAGE = https://xfce.org/
ARCHIVE = xfce4-settings-4.21.1.tar.xz
LINK = https://archive.xfce.org/src/xfce/xfce4-settings/4.21/xfce4-settings-4.21.1.tar.xz 
SRCCD = archive
BUILD = meson
BUILDDIR = xfce4-settings-4.21.1
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
