COMMENT = Simple man page generator written for POSIX systems written in C99
VERSION = 1.11.4
REVISION = 0
CATEGORIES = doc
PKGNAME = scdoc
HOMEPAGE = https://git.sr.ht/~sircmpwn/scdoc
ARCHIVE = 1.11.4.tar.gz
LINK = https://git.sr.ht/~sircmpwn/scdoc/archive/1.11.4.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = scdoc-1.11.4
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
