COMMENT = girara - gtk user interface that focuses on simplicity and minimalism
VERSION = 2026.02.04
REVISION = 0
CATEGORIES = libs
PKGNAME = girara
HOMEPAGE = https://git.pwmt.org/pwmt/girara
ARCHIVE = girara-2026.02.04.tar.xz
LINK = https://pwmt.org/projects/girara/download/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = girara-2026.02.04
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
