COMMENT = st - simple terminal (wayland version)
VERSION = 0.c0d5f6883
_REV = 0d5f68831ef4c6fbeb98fa0ab08ee0cae565b2aa
REVISION = 0
CATEGORIES = wayland
PKGNAME = st_wl
HOMEPAGE = https://github.com/marchaesen/st-wl
ARCHIVE = ${_REV}.tar.gz
LINK = https://github.com/marchaesen/st-wl/archive/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = st-wl-${_REV}
MAKEOPT =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
