COMMENT = Clean C library for processing UTF-8 Unicode data
VERSION = 2.11.2
REVISION = 0
CATEGORIES = libs
PKGNAME = utf8proc
HOMEPAGE = https://github.com/JuliaLang/utf8proc
ARCHIVE = utf8proc-2.11.2.tar.gz
LINK = https://github.com/JuliaLang/utf8proc/archive/v2.11.2/utf8proc-2.11.2.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = utf8proc-2.11.2
MAKEOPT = prefix=/usr

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
