COMMENT = X11 Direct Graphics Access extension library
VERSION = 1.1.6
REVISION = 0
CATEGORIES = libs
PKGNAME = libXxf86dga
HOMEPAGE = https://wiki.freedesktop.org/xorg/
ARCHIVE = libXxf86dga-1.1.6.tar.xz
LINK = https://www.x.org/releases/individual/lib/libXxf86dga-1.1.6.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = libXxf86dga-1.1.6
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

custom-build:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
