COMMENT = SELinux binary policy manipulation library
VERSION = 3.8.1
REVISION = 0
CATEGORIES = libs
PKGNAME = libsepol
HOMEPAGE = https://github.com/SELinuxProject/selinux/wiki
ARCHIVE = libsepol-3.8.1.tar.gz
LINK = https://github.com/SELinuxProject/selinux/releases/download/3.8.1/libsepol-3.8.1.tar.gz
SRCCD = archive
BUILD = make
BUILDDIR = libsepol-3.8.1
MAKEOPT = SHLIBDIR="/usr/lib"

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
