COMMENT = X Rendering Extension client library
VERSION = 0.9.12
REVISION = 0
CATEGORIES = libs
PKGNAME = libXrender
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXrender-0.9.12.tar.xz
LINK = https://www.x.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = make
BUILDDIR = libXrender-0.9.12
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
