COMMENT = Window Navigator Construction Kit
VERSION = 43.3
REVISION = 0
CATEGORIES = libs
PKGNAME = libwnck3
HOMEPAGE = https://gitlab.gnome.org/GNOME/libwnck
ARCHIVE = libwnck-43.3.tar.xz
LINK = https://download.gnome.org/sources/libwnck/43/libwnck-43.3.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = libwnck-43.3
BUILD_OPTION = -Dgtk_doc=false

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
