COMMENT = xorg xcvt library and cvt program
VERSION = 0.1.3
REVISION = 0
CATEGORIES = libs
PKGNAME = libxcvt
HOMEPAGE = https://gitlab.freedesktop.org/xorg/lib/libxcvt
ARCHIVE = libxcvt-${VERSION}.tar.xz
LINK = https://xorg.freedesktop.org/releases/individual/lib/${ARCHIVE}
SRCCD = archive
BUILD = meson
BUILDDIR = libxcvt-${VERSION}

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
