COMMENT = A Xlib-compatible API for the Present extension
VERSION = 1.0.2
REVISION = 0
CATEGORIES = libs
PKGNAME = libXpresent
HOMEPAGE = https://xorg.freedesktop.org/
ARCHIVE = libXpresent-1.0.2.tar.xz
LINK = https://www.x.org/releases/individual/lib/libXpresent-1.0.2.tar.xz
SRCCD = archive
BUILD = make
BUILDDIR = libXpresent-1.0.2
AUTO_CONF = (cd ${BUILDDIR} && ./configure --prefix=/usr --sysconfdir=/etc)

prepare:

custom-build:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
