COMMENT = Image viewer for X11/Wayland
VERSION = 5.0.1
REVISION = 0
CATEGORIES = tool
PKGNAME = imv
HOMEPAGE = https://sr.ht/~exec64/imv
ARCHIVE = v5.0.1.tar.gz
LINK = https://git.sr.ht/~exec64/imv/archive/v5.0.1.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = imv-v5.0.1
BUILD_OPTION = -Dwindows=all \
	-Dtest=disabled \
	-Dunicode=grapheme

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
