COMMENT = GStreamer streaming media framework libav plugin
VERSION = 1.28.3
REVISION = 0
CATEGORIES = libs
PKGNAME = gst_libav
HOMEPAGE = https://gstreamer.freedesktop.org
ARCHIVE = gst-libav-1.28.3.tar.xz
LINK = https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.28.3.tar.xz
SRCCD = archive
BUILD = meson
BUILDDIR = gst-libav-1.28.3
BUILD_OPTION =

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
