COMMENT = A thin layer of graphic data types
VERSION = 1.10.8
REVISION = 0
CATEGORIES = libs
PKGNAME = graphene
HOMEPAGE = http://ebassi.github.io/graphene/
ARCHIVE = graphene-1.10.8.tar.gz
LINK = https://github.com/ebassi/graphene/archive/1.10.8/graphene-1.10.8.tar.gz
SRCCD = archive
BUILD = meson
BUILDDIR = graphene-1.10.8
BUILD_OPTION = -Dinstalled_tests=false -Dintrospection=enabled

prepare:

post_build:

post-install:

include /usr/share/mk/lfs.port.mk
